version: '3'

networks:
  project-network:
    driver: bridge

volumes:
  mongodb_data_cont:

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - project-network

  kafka_broker1:
    image: bitnami/kafka:latest
    container_name: kafka_broker1
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - project-network

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    networks:
      - project-network
    depends_on:
      - kafka_broker1
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka_broker1:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka_broker1:9092 --create --if-not-exists --topic RedditsTopic --replication-factor 1 --partitions 10
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka_broker1:9092 --list
      "

  consumer1:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  consumer2:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  consumer3:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  consumer4:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  consumer5:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  consumer6:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  consumer7:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  consumer8:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  consumer9:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  consumer10:
    build:
      context: ./consumer
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        # Run the client code
        python -u main.py

  generator1:
    build:
      context: ./generator
    networks:
      - project-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 35
        # Run the client code
        python -u main.py

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - project-network
    ports:
    - 27017:27017
    volumes:
    - mongodb_data_cont:/data/db
